Promises instead callbacks. Now server not crashed if send bad token.
HowProgrammingWorks/Session pull request #3
Opened 2023-03-22 18:15 UTC by OsirisAnubis

1. All callback into `storage.js` to promise (async/await).
1.1. Now function `safePath` takes a promise as the first argument and return promise, instead callback contract.
`const safePath = (fn) => (token, ...args) => {`
`const safePath = (promise) => (token, ...args) => {`
1.2. All methods in Storage async. This method await safePath promises.
`async get(key) {`
`data = await readSession(key);`
`async save(key) {`
`await writeSession(key, data);`
`async delete(key) {`
`await deleteSession(key);`
2. Storage return `undefined` if not found file session.
```
try {
  data = await readSession(key);
} catch (err) {
  return undefined;
}
```
This makes Storage contract look more like Map contract(if not found return `undefined`).
3. Session.restore method
```
static restore(client) {
  const { cookie } = client;
  if (!cookie) return;
  const sessionToken = cookie.token;
  if (sessionToken) {
    return new Promise((resolve, reject) => {
      storage.get(sessionToken, (err, session) => {
        if (err) reject(new Error('No session'));
        Object.setPrototypeOf(session, Session.prototype);
        client.token = sessionToken;
        client.session = session;
        resolve(session);
      });
    });
  }
}
```
```
static async restore(client) {
  const { cookie } = client;
  if (!cookie) return;
  const sessionToken = cookie.token;
  if (!sessionToken) return;
  const session = await storage.get(sessionToken);
  if (!session) return;
  Object.setPrototypeOf(session, Session.prototype);
  client.token = sessionToken;
  client.session = session;
  return session;
}
```
Now if you pass a bad token, the server will not crash.

2023-03-22 21:02 UTC, tshemsedinov requested changes
Please make separate example in new folder instead changing callback-style code. For example move `JavaScript` to `JavaScript/Callbacks` and put this example to `JavaScript/AsyncAwait`

2023-03-22 21:02 UTC, tshemsedinov commented on JavaScript/storage.js
> +const safePath = (promise) => (token, ...args) => {
`promise` is not an instance of `Promise`, it's an `AsyncFunction` so naming is confusing

2023-03-22 21:02 UTC, tshemsedinov commented on JavaScript/storage.js
> +    } catch (err) {
`err` defined but not used

2023-03-23 10:15 UTC, OsirisAnubis commented on JavaScript/storage.js
> +    } catch (err) {
Would it be better to create 2 pull requests? First for fix crashing server. Second for async/await syntax.

2023-03-23 11:09 UTC, tshemsedinov commented on JavaScript/storage.js
> +    } catch (err) {
It would be better to open separate PRs from different branches

2023-03-23 11:28 UTC, OsirisAnubiz commented on JavaScript/storage.js
> +    } catch (err) {
Thank you. I will do as you said. I apologize for the inconvenience.

2023-03-23 12:08 UTC, closed without merging